name: 'Ekite composite example'
description: 'Return a tagged version'
outputs:
  tagged-version:
    description: "Ekite Tagged version"
    value: ${{ steps.tag-version.outputs.tagged-version }}
runs:
  using: "composite"
  steps:
  - id: tag-version
    shell: bash
    run: |
      VERSION=$(jq -r .version package.json)
      echo "tagged-version=$VERSION-ekite" >> $GITHUB_OUTPUT